version: '3.8'
services:
  db:
    image: postgres:15
    container_name: crypto_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=senha_forte
      - POSTGRES_DB=cryptoadvisor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
